services:
  - type: web
    name: book-reading-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --threads 100 --workers 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "0"
